### ISSUE TITLE
Add styled-components

### ISSUE THREAD

**Issue by laisfrigerio** [Lukenoutte/datacovid-api-reactjs#1]
Olá

Posso contribuir no projeto adicionando a lib `styled-components` para a estilização?

**Comment by Lukenoutte** [comment]
Oi Laís, pode sim, nunca utilizei styled-componentes vai ser interessante
ver como funciona.

Em sáb, 3 de out de 2020 00:56, Lais Frigério <notifications@github.com>
escreveu:
